### ISSUE TITLE
Add user's panel

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/groceries-app#2]
An user should be able to send, edit and delete **their own products**, but not _other user's products_.

To get this, we need to add a simple user's panel where they can view, add, delete or update their submissions. 

- Submissions can be global or local
- Global submissions need to be approved before being listed

### Tasks list
- [ ] Create user panel
- [ ] Restrict user panel to verified users
- [ ] Allow users to view submissions status
- [ ] Allow users to send submissions
- [ ] Allow users to delete or update their own submissions
