### ISSUE TITLE
Add registration form

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/groceries-app#3]
Allow users to sign up into the app with a formulary.

- Since first release will be a beta, I don't want to collect users' emails, so we need to switch user ID as username instead of email
- Closed beta: to be able to sign up you need also a key or host it yourself.

### Tasks list
- [ ] Create beta keys model
- [ ] Modify User model to allow sign up without email
- [ ] Add User creation form
